site_name: Cloud Documentation
extra:
  social:
    - icon: simple/github
      link: https://github.com/AMohamed0
  generator: false
nav:
  - Home:
    - Introduction: 'index.md'
  - Labs:
    - AWS: 
      - "AWS Introduction": 'AWS.md'
      - "Resizing-Image": 'Lambda.md'
    - Azure:
      - "Azure Introduction": 'AZURE.md'
    - GCP:
      - "GCP Introduction": 'GCP.md'
  - Projects:
      - "devops": 'DevOps.md'
plugins:
  - glightbox
  - search
repo_url: https://github.com/AMohamed0
theme:
  icon:
    repo: fontawesome/brands/github
    admonition: 
      note: octicons/tag-16
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.instant
    - navigation.instant.progress
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - navigation.expand
    - navigation.path
    - header.autohide
    - navigation.footer
  language: en
  palette:
# Palette toggle for light mode
    - scheme: default
      toggle: 
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: blue grey
      accent: deep purple

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
      primary: blue grey
      accent: deep purple
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true



copyright: |
  &copy; 2023 <a href="https://github.com/AMohamed0/CloudDocs/blob/main/LICENSE"  target="_blank" rel="noopener">AMohamed0</a>
